name: CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Install dependencies'
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
      - name: 'Run tests'
        uses: php-actions/phpunit@v3